#!/bin/zsh
PROJECT="CerebralLine.Reading"
WT="Work3"
TMP_FILE="/tmp/taaddbook.tmp"

create_tasks() {
    if [[ ! -n "$MAIN_TASK_ID" ]]; then
        MAIN_TASK_ID=$(task add "$BOOK_DESCRIPTION" \
            project:"$PROJECT" STATE:Info STYLE:"$STYLE" WT:"$WT" \
            +WithScript | grep -oP '(?<=Created task ).*' | sed -E 's/\.//g')

        sleep 2
        clear
    fi

    echo "You need to write the subtasks descriptions."
    echo "Separate they by linebreaks and save it!"
    echo "!! And don't forget, the code was already entered, don't write it."
    $VISUAL "$TMP_FILE"

    SUBTASKS_DESCRIPTIONS=$(cat "$TMP_FILE")

    rm "$TMP_FILE"
    while IFS= read -r DESCRIPTION; do
        taaddsub "$MAIN_TASK_ID" "$BOOK_CODE: $DESCRIPTION" \
        STYLE:"$STYLE" +Sequence +WithScript WT:"$WT"
    done <<< $(echo "$SUBTASKS_DESCRIPTIONS")
}
confirm_and_create() {
    ANSWERED=0;

    while [[ $ANSWERED == 0 ]]; do
        printf "Do you want to continue? [y/n]: "
        read -r ANSWER

        if [[ "$ANSWER" == "y" ]]; then
            clear

            create_tasks

            ANSWERED=1;
        elif [[ "$ANSWER" == "n" ]]; then
            echo "Try to fix it!"

            ANSWERED=1;
        else
            echo "Only 'y' and 'n' are allowed! Try again."
        fi
    done
}
print_usage() {
    echo "Usage: taaddbook [OPTIONS] [ARGS]

If you use '-a' as an option:
        taaddbook -a <book_code> <main_task_id>
Else:
        taaddbook <book_code> <book_description> <style>
"
}

clear
if [[ "$1" == "-a" ]]; then
    shift

    if [[ $# -eq 2 ]];then

        BOOK_CODE=$1
        MAIN_TASK_ID=$2
        MAIN_TASK_JSON=$(task "$MAIN_TASK_ID" export)
        STYLE=$(echo "$MAIN_TASK_JSON" | jq -r '.[].STYLE')

        echo "Book Code: $BOOK_CODE"
        echo "Main Task:"
        echo "$MAIN_TASK_JSON" | jq -C
        echo ""

        confirm_and_create
    else
        print_usage

        exit 1
    fi
else
    if [[ $# -eq 3 ]]; then
        BOOK_CODE=$1
        BOOK_DESCRIPTION=$2
        STYLE=$3

        echo "Book Code: $BOOK_CODE"
        echo "Book Description: $BOOK_DESCRIPTION"
        echo "Task Style: $STYLE"
        echo ""

        confirm_and_create
    else
        print_usage

        exit 1
    fi
fi


