#!/bin/zsh
ID="$1"
TIME="$2"

warn() {
    echo "$1"
    echo "Usage: tasal <task_id> <time_to_schedule>"
}

if [[ $# -eq 0 ]]; then
    warn "Do you need to specify something!"
elif [[ $# -eq 1 ]]; then
    warn "Do you need to specify a time!"
elif [[ $# -gt 2 ]]; then
    warn "Too many args!"
else
    task "$ID" modify ALARM:"$TIME"

    echo "\nThe task with id '$ID' was scheduled to be warned at '$TIME'!"
fi
