#!/bin/zsh

usage() {
    echo "Usage: oopen-prog <binary_name> - Once-Open Program"
    echo
    echo "Trick: Specify the full path to the binary if it is not working correctly."
}
verify_args() {
    if [[ $# -eq 1 ]]; then
        if [[ $1 == --help || $1 == -h ]]; then
            usage
            exit 0
        else
            BINARY=$1
        fi
    else
        usage
        return 1
    fi
}
main() {
    BINARY_PATH=$(which $BINARY)

    if [[ $? -ne 0 ]]; then
        echo "Binary not found"
        return 1
    fi

    PID=$(pgrep -f --exact "$BINARY_PATH")

    if [[ -z $PID ]]; then
        zsh -c $BINARY_PATH > /dev/null 2>&1 & disown
    else
        echo "It is already running."
    fi
}
verify_args $@ || exit 1
main
