#!/bin/bash
# $1 = Playlist Name
# $2 = Number of Musics

PLAYLIST_NAME=$1
MUSIC_LENGTH=$2
PROJECT="Music.Playlist"
STYLE="Dionysian"
TYPE="Objective"

usage() {
    echo "Usage: taadd-msc <PLAYLIST_NAME> <MUSIC_LENGTH>"
}
if [ $# -lt 2 ]; then
    usage

    exit 1
fi

main() {
    MOTHER_ID=$(yes | taadd "$PLAYLIST_NAME" "$PROJECT" "$STYLE" "$TYPE" | grep -oP 'Created task \K\d+(?=\.)')

    taaddsub "$MOTHER_ID" "Photo" STYLE:"$STYLE"
    taaddsub "$MOTHER_ID" "Description" STYLE:"$STYLE"
    taaddsub "$MOTHER_ID" "Musics ($MUSIC_LENGTH)" STYLE:"$STYLE"
}

main
