#!/bin/zsh

usage() {
    echo "Usage: tacodel"
}
verify_args() {
    if [[ $# -ne 0 ]]; then
        usage
        return 1
    fi
}
main() {
    ARCHIVED=$(task "+Archived" export | jq -r 'length')
    FAILED=$(task "+Failed" export | jq -r 'length')
    ABANDONED=$(task "+Abandoned" export | jq -r 'length')
    NOCONTROL=$(task "+NoControl" export | jq -r 'length')

    echo "All archived tasks: $ARCHIVED"
    echo "All failed tasks: $FAILED"
    echo "All abandoned tasks: $ABANDONED"
    echo "All nocontrol tasks: $NOCONTROL"
}
verify_args $@ || exit 1
main
