#!/bin/zsh
# $1 = Property
# $2 = Modifier
if [[ $# -eq 0 ]]; then
    echo "Do you need to specify a property!"

    exit 1
fi
if [[ $# -eq 1 ]]; then
    echo "Do you need to specify a modifier!"
    
    exit 1;
fi

PROPERTY=$1
MODIFIER=$2
VERBOSE="rc.verbose=false"

shift
shift

if [[ $# -gt 0 ]]; then
    case "$1" in
        "-y")
            shift

            if [[ -n "$1" ]]; then
                YEAR="$1"
                shift

                INITIAL_DATE="${YEAR}-01-01T00:00"
                FINAL_DATE="$(date -d "${YEAR}-01-01 +1 year" '+%Y-01-01')T00:00"
            else
                INITIAL_DATE="$(date +%Y-01-01)T00:00"
                FINAL_DATE="$(date -d "$(date +%Y-01-01) +1 year" '+%Y-01-01')T00:00"
            fi

            ;;
        "-m")
            shift
            if [[ -n "$1" ]]; then
                MONTH="$1"
                shift

                INITIAL_DATE="$(date "+%Y-${MONTH}-01")T00:00"
                FINAL_DATE="$(date -d "$(date +%Y-${MONTH}-01) +1 month" '+%Y-%m-01')T00:00"
            else
                INITIAL_DATE="$(date '+%Y-%m-01')T00:00"
                FINAL_DATE="$(date -d "$(date +%Y-%m-01) +1 month" '+%Y-%m-01')T00:00"    
            fi
            ;;
        "-w")
            shift

            if [[ -n "$1" ]]; then
                WEEK_NUMBER=$1
                shift

                INITIAL_DATE=$(date -d "$(date +%Y-%m-01) \
                    +$(($WEEK_NUMBER - 1)) Week" '+%Y-%m-%dT%H:%M')
                FINAL_DATE=$(date -d "$(date +%Y-%m-01) \
                    +$WEEK_NUMBER Week" '+%Y-%m-%dT%H:%M')
            else
                DATE_STR="$(date +%u) days ago"

                INITIAL_DATE=$(date -d "$DATE_STR +1 day" +'%Y-%m-%dT00:00')
                FINAL_DATE=$(date -d "$DATE_STR +1 week +1 day" +'%Y-%m-%dT00:00')
            fi
            ;;
        *)
            echo "Only '-y', '-w' and '-m' are supported!"
            exit 1
            ;;
    esac

    echo "Showing tasks with the $PROPERTY between $INITIAL_DATE -> $FINAL_DATE:"
    echo ""

    task "\(($PROPERTY.after:$INITIAL_DATE or $PROPERTY:$INITIAL_DATE) and $PROPERTY.before:$FINAL_DATE)" \
        "$VERBOSE" "${@}" "$MODIFIER"
else
    echo "Showing tasks with any $PROPERTY:"
    echo ""

    task "$PROPERTY.any:" "$VERBOSE" "${@}" "$MODIFIER"
fi
