#!/bin/zsh

while true; do
    TASKS_LENGTH=$(task +ACTIVE export | jq -r '. | length')
    
    if [[ $TASKS_LENGTH -eq 0 ]]; then
        tastart "$(tgetid "Time without specific use")"

        LAST_TIMEW_END=$(timew export @2 | jq -r '.[0].end')
        CURRENT_TIMEW_START=$(timew export @1 | jq -r '.[0].start')

        if [[ "$LAST_TIMEW_END" != "$CURRENT_TIMEW_START" ]]; then
            tiend @2 "$CURRENT_TIMEW_START"
        fi
    fi

    sleep 10
done
