#!/bin/bash

DOMAIN="$1"
SITE_IPS=$(dig +short "$DOMAIN")

echo "$SITE_IPS" | while read -r line; do
    echo "Removed REJECT iptables rule to: $line"
    sudo iptables -D OUTPUT -d "$line" -j REJECT
done
