#!/bin/bash
# $1 = Temporada
# $2 = Episódio
# $3 = ID da tarefa pai

CREATED_ID=$(task add "PLL: T$1E$2" project:Assistir \
    STYLE:Dionysian TYPE:SubTask | grep -oP "Created task \K\d+(?=\.)")

task "$3" modify depends:"$CREATED_ID"

task "$CREATED_ID" modify MOTHER:"$(task "$3" export | jq -r '.[0].uuid')"
