#!/bin/bash
# $1 = Nome da Playlist
# $2 = Número de Músicas

TASK=$(task add "$1" project:Music +STYLE.Dionysian +TYPE.Objective +WT.NonSched | grep -oP 'Created task \K\d+(?=\.)')

taaddsub "$TASK" "Foto" project:Music +STYLE.Dionysian +WT.NonSched
taaddsub "$TASK" "Descrição" project:Music +STYLE.Dionysian +WT.NonSched
taaddsub "$TASK" "Músicas ($2)" project:Music +STYLE.Dionysian +WT.NonSched
