#!/bin/bash

# $1 = Main task ID 
# $2 = Sub task description
# ${@:3} = Other attributes
taskProject=$(task "$1" _projects)

newTaskStr=$(task add "$2" project:"$taskProject" "${@:3}" TYPE:SubTask)
newTaskID=$(echo "$newTaskStr" | grep 'Created task' | grep -o '[0-9]\+')

task "$1" modify depends:"$newTaskID"

task "$newTaskID" modify MOTHER:"$(task "$1" export | jq -r '.[0].uuid')"
