#!/bin/zsh
# $1 = Type
# $2 = Description
# $3 = Tag
# $4 = Temp Number
# $5 = Sequence/Temp Last Episode Number
# $6 = Initial Ep Number
# $7 = Last Temp ID

TYPE=$1
DESCRIPTION=$2
TAG=$3
INITIAL=$4
LAST=$5

usage() {
    echo "Usage: taadd-seq _<TYPE> <DESCRIPTION> <TAG> <INITIAL_NUMBER> <LAST_NUMBER> [TEMP] [LAST_TEMP_ID]"
}
verify_args() {
    if [[ $# -lt 5 ]]; then
        usage
        return 1
    elif [[ $# -gt 7 ]]; then
        usage
        return 1
    else
        if [[ -n $6 ]]; then
            if [[ "$TYPE" == "Book" ]]; then
                echo "You cannot specify TEMP if you are creating a book!"
                return 1
            else
                TEMP=$6
            fi
        fi
        if [[ -n $7 ]]; then
            LAST_TEMP_ID=$7
        fi
    fi
}
get_uuid() {
    read -r INPUT
    ID=$(echo $INPUT | grep -oP 'Created task \K\d+(?=\.)')
    task "$ID" uuids
}
main() {
    if [[ "$TYPE" == "Book" ]]; then
        PROJECT="CerebralLine.Reading"
    else
        PROJECT="Lazer.Watch"
    fi

    if [[ -n $TEMP ]]; then
        MOTHER_DESC="$DESCRIPTION (Temp $TEMP)"
    else
        MOTHER_DESC="$DESCRIPTION"
    fi

    MOTHER_UUID=$(fypm ta-add -y "$MOTHER_DESC" "$PROJECT" Dionysian Objective +Sequence "+ST_$TAG" "+$TYPE" | get_uuid)
    for ((i=$INITIAL; i <= $LAST; i++)); do
        if [[ "$TYPE" == "Book" ]]; then
            DESCRIPTION="Capítulo $i"
        else
            if [[ -n $TEMP ]]; then
                DESCRIPTION="T${TEMP}E$i"
            else
                DESCRIPTION="E$i"
            fi
        fi

        ARGS=("$MOTHER_UUID" "$DESCRIPTION" "Dionysian" "+ST_$TAG" "+Sequence" "+$TYPE")

        if [[ $i -eq $INITIAL ]]; then
            if [[ -n $LAST_TEMP_ID ]]; then
                LAST_TEMP_LAST_EP_UUID=$(task MOTHER:"$(task $LAST_TEMP_ID uuids)" SEQ_NEXT: uuids)
                ARGS+=("SEQ_PREVIOUS:$LAST_TEMP_LAST_EP_UUID")
            fi

            # Create new task
            CURRENT_TASK_UUID=$(taaddsub "${ARGS[@]}" | get_uuid)

            if [[ -n $LAST_TEMP_ID ]]; then
                task "$LAST_TEMP_LAST_EP_UUID" modify SEQ_NEXT:"$CURRENT_TASK_UUID"
            fi

            # Set current to mother
            task "$MOTHER_UUID" modify SEQ_CURRENT:"$CURRENT_TASK_UUID"

            # Set current task as previous on variable
            PREVIOUS_TASK_UUID=$CURRENT_TASK_UUID
        else
            if [[ -n $PREVIOUS_TASK_UUID ]]; then
                # Create new task and set your previous task
                CURRENT_TASK_UUID=$(taaddsub "${ARGS[@]}" | get_uuid)

                # Set next and previous UDA's
                task "$CURRENT_TASK_UUID" modify SEQ_PREVIOUS:"$PREVIOUS_TASK_UUID"
                task "$PREVIOUS_TASK_UUID" modify SEQ_NEXT:"$CURRENT_TASK_UUID"

                # Set current task as previous on variable
                PREVIOUS_TASK_UUID=$CURRENT_TASK_UUID
            else
                echo "Something went wrong! The iterator isn't the initial ep, but has no previous task id!"
                exit 1
            fi
        fi
    done
}
verify_args $@ || exit 1
main
