#!/bin/zsh

usage() {
    echo "Usage: taadd-brth <birthday_person> <date>"
    echo
    echo "    <date>: MM-DD"
}
verify_args() {
    if [[ $# -eq 2 ]]; then
        NAME=$1
        DATE=$2

        if ! date -d "$(date +%Y)-$DATE" > /dev/null 2>&1; then
            echo "You entered an invalid date!"
            return 1
        fi
    else
        usage
        return 1
    fi
}
main() {
    CURRENT_YEAR=$(date +%Y)

    if [[ $(date -d "$CURRENT_YEAR-$DATE" +%Y%m%d) -lt $(date +%Y%m%d) ]]; then
        FINAL_DATE=$(date -d "$(( CURRENT_YEAR + 1 ))-$DATE" +%Y-%m-%d)
    else
        FINAL_DATE=$(date -d "$CURRENT_YEAR-$DATE" +%Y-%m-%d)
    fi

    taadd "$NAME's Birthday" Social.Events Dionysian Event \
        WT:AllDay! GOAL:"${FINAL_DATE}T00:00:00" due:"${FINAL_DATE}T23:59:59" recur:yearly
}
verify_args $@ || exit 1
main
