#!/bin/zsh

usage() {
    echo "Usage: taandl"
}
verify_args() {
    if [[ ! $# -eq 0 ]]; then
        usage
        return 1
    fi
}
main() {
    task rc.report.next.labels=ID,Type,WT,Due,Description,Urg rc.report.next.columns=id,TYPE,WT,due.relative,description,urgency next
}
verify_args $@ || exit 1
main
