#!/bin/zsh
ABANDONED="false"
FAILED="false"
NOCONTROL="false"

usage() {
    echo "Usage: taban <-a, abandoned | -f, failed | -n, no-control> <task_id> [annotation]"
}
main() {
    local TASKS_LENGHT
    TASKS_LENGHT=$(task "$ID" count)

    if [[ "$ABANDONED" == "true" ]]; then
        if [[ "$TASKS_LENGHT" -gt 2 ]]; then
            oyes "all" "no" | task "$ID" modify +Abandoned
        else
            yes "no" | task "$ID" modify +Abandoned
        fi
    elif [[ "$FAILED" == "true" ]]; then
        if [[ "$TASKS_LENGHT" -gt 2 ]]; then
            oyes "all" "no" | task "$ID" modify +Failed
        else
            yes "no" | task "$ID" modify +Failed
        fi
    elif [[ "$NOCONTROL" == "true" ]]; then
        if [[ "$TASKS_LENGHT" -gt 2 ]]; then
            oyes "all" "no" | task "$ID" modify +NoControl
        else
            yes "no" | task "$ID" modify +NoControl
        fi
    fi

    if [[ "$TASKS_LENGHT" -gt 1 ]]; then
        oyes "all" "no" | task "$ID" delete
    else
        oyes "yes" "no" | task "$ID" delete
    fi
}

if [[ $# -gt 3 ]]; then
    echo "Too many arguments!"
    usage
    exit 1
elif [[ $# -lt 2 ]]; then
    echo "Not enough arguments!"
    usage
    exit 1
else
    OPTION=$1
    ID=$2
    ANNOTATION=$3 # Optional

    case "$OPTION" in
        "-f" | "--failed")
            FAILED="true"
            ;;
        "-n" | "--no-control")
            NOCONTROL="true"
            ;;
        "-a" | "--abandoned")
            ABANDONED="true"
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac

    if [[ $# -eq 3 ]]; then
        tan "$ID" "$ANNOTATION"
    fi
fi

main
