#!/bin/zsh
# $1 = Goal ID
# $2 = Goal Init Date
# $3 = Goal Finish Date (due)
ID=$1
GOAL=$2
DUE=$3

if [[ -z "$ID" ]]; then
    echo "Do you need to specify a ID!"
    exit 1
fi
if [[ -z "$GOAL" ]]; then
    echo "Do you need to specify a goal date!"
    exit 1
fi

TYPE=$(task "$ID" export | jq -r '.[0].TYPE')

if [[ "$TYPE" == "Continuous" || "$TYPE" == "Essential" ]]; then
    echo "You can't set a goal to a $TYPE task!"
    echo "You need to use the schedule feature! Try 'tsched' :)"
fi

if [[ -n "$DUE" ]]; then
    task "$ID" modify GOAL:"$GOAL" due:"$DUE"
else
    task "$ID" modify GOAL:"$GOAL"
fi
