#!/bin/bash

LAST_TASK_PATH=/tmp/.last_task

if [[ -n "$1" ]]; then
    task "$1" stop
else
    RECEIVE_ACTIVES=$(task +ACTIVE export)
    ACTIVES_LENGTH=$(echo "$RECEIVE_ACTIVES" | jq 'length')

    if [[ "$ACTIVES_LENGTH" -eq 0 ]]; then
        echo "There's no active task"
        exit 1
    elif [[ "$ACTIVES_LENGTH" -eq 1 ]]; then
        task "$(echo "$RECEIVE_ACTIVES" | jq -r '.[0].id')" stop

        task "$1" export | jq -r '.[0].uuid' | sed 's/-.*//' > "$LAST_TASK_PATH"
    else
        echo "There's more than one active task!"
        exit 1
    fi

    task "$(tgetid 'Time without specific use' WT:Quantify)" start
fi
