#!/bin/bash
# $1 = Main Task Id 
# $2 = Subtask Id

MAIN_TASK_UUID=$(task "$1" uuids)
MAIN_TASK_PROJECT=$(task "$1" export | jq -r '.[0].project')

task "$2" modify project:"$MAIN_TASK_PROJECT" MOTHER:"$MAIN_TASK_UUID" TYPE:SubTask

task "$1" modify depends:"$2"
