#!/bin/zsh

if [[ "$1" == "-d" ]]; then
    task "$2" modify status:pending -Abandoned -Failed -NoControl
elif [[ "$1" == "-c" ]]; then
    task "($2) and +Archived)" modify status:pending -Archived
else
    task "$1" modify status:pending
fi
