#!/bin/zsh

if [[ $# -eq 0 ]]; then
    tistart @1 "$(timew export @3 | jq -r '.[0].end')"
elif [[ $# -eq 1 ]]; then
    tistart "$1" "$(timew export @3 | jq -r '.[0].end')"
elif [[ $# -eq 2 ]]; then
    tistart "$1" "$(timew export "$2" | jq -r '.[0].end')"
else
    echo "Usage: ticart [tomodify_task_start](default: @1) [static_task_end](default: @3)"
fi
