#!/bin/zsh
# $1: Date / verbose
# $2: Date / Description
# $3: Description

alias tils="timew summary :ids"

calculate_time() {
    if [[ -n "$2" ]]; then
        TASK_DESC="$2"
    else
        TASK_DESC="Sleep"
    fi

    INITIAL_SLEEP=$(tils 10h before "$1" "$TASK_DESC" | tail -n 2 | tr -d ' ')

    FINAL_SLEEP=$(tils "$1" for 10h "$TASK_DESC" | tail -n 2 | tr -d ' ')

    IFS=":" read -r h1 m1 s1 <<< "$INITIAL_SLEEP"
    IFS=":" read -r h2 m2 s2 <<< "$FINAL_SLEEP"
    INITIAL_SECS=$((h1*3600 + m1*60 + s1))
    FINAL_SECS=$((h2*3600 + m2*60 + s2))

    # Some os segundos
    TOTAL_SECS=$((FINAL_SECS + INITIAL_SECS))

    # Converta os segundos de volta para horas, minutos e segundos
    HOURS=$((TOTAL_SECS / 3600))
    MINUTES=$(( (TOTAL_SECS % 3600) / 60 ))
    SECONDS=$((TOTAL_SECS % 60))

    TIME_IN_BED=$((TOTAL_SECS / 60))

    printf "Total Sleep: %02d:%02d:%02d (%02dm)\n" \
        "$HOURS" "$MINUTES" "$SECONDS" "$TIME_IN_BED"

    printf "How long did it take before you fell sleep? (minutes): "
    read -r BEFORE_ASLEEP_TIME

    SLEEP_POINTS=$(sleepc.mjs $TIME_IN_BED $BEFORE_ASLEEP_TIME)
    echo "Sleep Points: $SLEEP_POINTS"

    SLEEP_TASK_UUID=$(task "Sleep" due.after:yesterday due.before:today uuids)

    if [[ -n "$SLEEP_TASK_UUID" ]]; then
        _ask_dialog "Do you want to record this in the sleep task?" || return

        tan "$SLEEP_TASK_UUID" "Time In Bed: $TIME_IN_BED (min)"
        tan "$SLEEP_TASK_UUID" "Time Before Asleep: $BEFORE_ASLEEP_TIME (min)"
        tan "$SLEEP_TASK_UUID" "Pure Sleep: $((TIME_IN_BED - BEFORE_ASLEEP_TIME)) (min)"
        tan "$SLEEP_TASK_UUID" "Sleep Points: $SLEEP_POINTS"
    else
        echo "No sleep task found!"
    fi
}

if [[ -z "$1" ]]; then
    if [[ "${@#}" -gt 1 ]]; then
        calculate_time today ${@:2}
    else
        calculate_time today
    fi
elif [[ "$1" == "-v" ]]; then
    if [[ -n "$3" ]]; then
        TASK_DESC="$3"
    else
        TASK_DESC="Sleep"
    fi
    if [[ -n "$2" ]]; then
        TASK_DAY="$2"
    else
        TASK_DAY="today"
    fi

    tils 10h before "$TASK_DAY" "$TASK_DESC"
    tils "$TASK_DAY" for 10h "$TASK_DESC"
else
    calculate_time "$1" "$2"
fi
